### ISSUE TITLE
Modules needed

### ISSUE THREAD

**Issue by anisoss** [aron-tn/Smtp-cracker#2]
modules are not installed there's something wrong with the code

**Comment by anisoss** [comment]
File "C:\Users\Pc\Desktop\smtp.py", line 24
    print"\033[91m[\033[92m?\033[91m] Installing emoji Module\033[00m"
                                                                     ^
SyntaxError: invalid syntax

**Comment by Aron-Tn** [comment]
Install python 2.7.1 !!

**Comment by anisoss** [comment]
doesn't include pip!!

**Comment by anisoss** [comment]
![Untitled](https://user-images.githubusercontent.com/47687978/55486100-a1359c00-5623-11e9-9550-e1838c31035e.png)

**Comment by Sicks3c** [comment]
@anisoss try install activepython in your windows and retry

**Comment by anisoss** [comment]
Where I put the packages please


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Sicks3c** [comment]
https://www.liquidweb.com/kb/install-pip-windows/
Install pip via this link and it will work
