### ISSUE TITLE
NameError: name 'requests' is not defined

### ISSUE THREAD

**Issue by LuongPhuHoa** [aron-tn/Smtp-cracker#3]
![image](https://user-images.githubusercontent.com/36793008/55814018-fc7df780-5b17-11e9-8ac1-a5644e5405e6.png)
Hello,i met this error,can you fix it for me please ?

**Comment by Aron-Tn** [comment]
Hi Bro u don't have python request for that u got this error !

Le mar. 9 avr. 2019 à 16:37, LuongPhuHoa <notifications@github.com> a
écrit :

**Comment by LuongPhuHoa** [comment]
i can run it now,but none of the smtp was worked bro

Vào Th 6, 12 thg 4, 2019 vào lúc 16:11 Amir othman <
notifications@github.com> đã viết:

**Comment by Aron-Tn** [comment]
Problem in ur combo bro ...

Le ven. 12 avr. 2019 à 13:55, LuongPhuHoa <notifications@github.com> a
écrit :

**Comment by Bleuff** [comment]
Hello ,
How did you fix it please ?

**Comment by Upgradetp** [comment]
bro i emailed you and wrote you on facebook with no answer im having the same issue with the request. I even typed in pip install requests and this is what it said:

λ pip install requests
Requirement already satisfied: requests in c:\python36\lib\site-packages (2.21.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\python36\lib\site-packages (from requests) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\python36\lib\site-packages (from requests) (2.6)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\python36\lib\site-packages (from requests) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in c:\python36\lib\site-packages (from requests) (2018.1.18)

Please help me

**Comment by Aron-Tn** [comment]
Hello bro !
for python version:
https://www.python.org/downloads/release/python-2716/
for resquest :
Try download this file
https://mega.nz/#!Mm5jEaIJ!RmpqYg76c_56tVWCvBfBLALHnOm1017dbNEz2HGBv_E
then Unzip it
open terminal and write "cd( to this folder (forlder request))" After that
write in terminal "setup.py install" he will install the request after that
run script smtp cracker he will be work without any error
thank you .

Le lun. 22 juil. 2019 à 05:46, Upgradetp <notifications@github.com> a
écrit :

**Comment by dahur119** [comment]
i have tried loading the smtp but it keeps cutting off when it tries to connect
